# Generated by Django 3.1.4 on 2020-12-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ring',
            new_name='Jewel',
        ),
    ]
